### ISSUE TITLE
Error in Build SMTSampler

### ISSUE THREAD

**Issue by jeevan0920** [RafaelTupynamba/SMTSampler#2]
I followed all the steps of installation.

During Build SMTSampler
while running make I got this error.

**_g++ -g -std=c++11 -O3 -o smtsampler smtsampler.cpp -lz3  
smtsampler.cpp:2:10: fatal error: z3++.h: No such file or directory
 #include <z3++.h>
          ^~~~~~~~
compilation terminated.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1_**

Do I need to include any Library Paths ?

**Comment by jeevan0920** [comment]
When I tried by including those header file paths.
I got this error.

**g++ -I ~/tools/z3/src/api/c++ -I ~/tools/z3/src/api/ -g -std=c++11 -O3 -o smtsampler smtsampler.cpp -lz3  
/usr/bin/ld: cannot find -lz3
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error _1**_

**Comment by jeevan0920** [comment]
I got the same errors while installing for your [GuidedSampler](https://github.com/RafaelTupynamba/GuidedSampler) also.

**Comment by RafaelTupynamba** [comment]
Hi,
I think this is probably because your z3 wasn't installed properly. The command
`sudo make install`
should install z3 in a way that the headers and libraries can be found.

If you don't have root access or don't want to install z3 for some reason, you can also try compiling this way (this worked for me):
`g++ -std=c++11 -g -O3 -I ../z3/src/api/c++ -I ../z3/src/api -Wl,-rpath ../z3/build -o smtsampler smtsampler.cpp ../z3/build/libz3.so`
